### ISSUE TITLE
Video recording of June presentations

### ISSUE THREAD

**Issue by pchinjr** [norfolkjs/logistics#102]
Hey everyone, I won't be able to make the June presentations. I can meet up with someone earlier that day to hand over the video/audio gear if you all want to keep recording it.

**Comment by lynnaloo** [comment]
@stanzheng @troy0820 @bmf Can one of you take over the video-recording for a night?

**Comment by bmf** [comment]
Sorry, I'm not going to be at this meetup.

**Comment by troy0820** [comment]
I'll give it my best shot, just guide me through what to do 👍

**Comment by lynnaloo** [comment]
The video didn't make it for this meetup, but I'm going to assign this to Paul to try to marry the audio with the slides.
