### ISSUE TITLE
February Agenda

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#107]
February 20th -"Sharpen Your Saw" 

Food Sponsor: Langa
Beer Sponsor: 80/20 Consoluting
Location Sponsor: Pierce/McCoy
Speaker Lodging Sponsor: Grow
Events: Revolution Conf (June 1-2), PopUp Robots, Fez, Late Night Coders

Feature Presentation: @shackbarth 
Lightning Talk(s): Troy Connor @troy0820

**Comment by troy0820** [comment]
Title of talk is "How you can contribute to Node.js"

**Comment by bmf** [comment]
Announcements are up. Can be seen here: http://rawgit.com/norfolkjs/general-info/master/announcements/february_2017.html
