### ISSUE TITLE
GlimmerJS

### ISSUE THREAD

**Issue by metaskills** [norfolkjs/logistics#113]
I almost drove down to NC to [see this talk](https://www.meetup.com/raleighrb/events/240030064/) and even [reached out](https://twitter.com/tddjordan/status/876821533708124161) to the speaker about coming up here.

If you look at the slides it is far less about Rails (not at all really) and more about GlimmerJS and modern web components. I'd really love to hear this talk and hang out with Todd. More about the speaker:

* https://twitter.com/tddjordan
* http://presentationtier.com
* https://github.com/toddjordan

**Comment by lynnaloo** [comment]
@metaskills we're booked up through November, but we could do a join meetup some other date? I'm definitely interested in this talk.
