### ISSUE TITLE
September Meetup

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#115]
September 18th - Title TBD Meetup

Food Sponsor: Langa
Beer Sponsor: Cloudreach
Location Sponsor: Pierce/McCoy
Events: PopUp Robots, HRDevFest

Talk(s):

Kenia Valladarez
Austin Galyon
Maurice Hayward

**Comment by moe-dizzle** [comment]
Javascript Closures: Are You Woke? 

Closures are among us and in your Javascript code! Don't be scared; this talk will help you to understand and leverage closures so that you can stay woke.

**Comment by kaxcode** [comment]
Math + Art = Code Masterpiece

Learn what SVG images are and how to create them for the web.

**Comment by austingalyon** [comment]
Breaking the Mold: Creating Desktop Apps with Electron

Everyone knows that HTML, CSS, and JavaScript power the web, but what if you could also use them to make a desktop application? We'll take a look at Electron, an open-source framework for creating native applications with HTML, CSS, and JavaScript, to learn how it works, how to use it, and look at some well known apps that it powers.

**Comment by lynnaloo** [comment]
@stanzheng are you still good to do the agenda for this meetup?

**Comment by qwo** [comment]
@lynnaloo sure
