### ISSUE TITLE
October Meetup

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#116]
October 16th - Lightning Talks

Food Sponsor: Langa
Beer Sponsor: CloudReach
Location Sponsor: Pierce/McCoy
Events: PopUp Robots, HRDevFest (Nov 10th)

Talk(s):

Dan Luhring
Troy Connor - MiniKube (Node Interactive Talk)

**Comment by lynnaloo** [comment]
@tjwebb once you get Dan's talk, this is ready for an event

**Comment by tjwebb** [comment]
Dan Luhring's talk info:

Abstract:

>If you’ve used JavaScript very much, you understand how rewarding it is to build things quickly in a thriving ecosystem with such a flexible language.  But even the most seasoned JavaScript developers spend more time than necessary resolving errors and other conundrums that could have been avoided in the first place.  TypeScript has rapidly gained popularity as a means of helping JavaScript developers realize and correct issues with their code more immediately than ever before.  Adding TypeScript to your JavaScript workflow is like bowling with bumpers -- but it feels less amateur, and it enables more winning.

>“TypeScript:  Work Smarter Not TypeError”

**Comment by troy0820** [comment]
Troy Connor's talk info:

Abstract:
> Learning Kubernetes is hard. Learning how to set up Kubernetes even harder. Developers have to provision a cluster from a cloud provider and have to start paying for that immediately. This can discourage developers who want to build scalable microservices. On big teams, usually, developers have a DevOps team who can take care of scalability and optimization. 

> When breaking apart monolithic applications, microservices will have to scale to handle the load of the incoming requests. As the application grows, so will the need for the microservices. When developing their applications, developers can run into the problem where it doesn't work in different environments. The phrase "It works on my machine" points fingers at a bigger problem. Developers can find this frustrating and it slows down updates to the application. The developer's workflow can prevent this by using minikube.

> For large enterprise applications who use the cloud as their platform, Kubernetes has been one of the many solutions to these issues. Quickly deploy, scale, and modernize your microservices with simple commands. Minikube allows you to test this functionality without the cloud provider. As a NodeJS developer, having the functionality to develop a workflow that you would use for your production application is very valuable.

> In this talk we will discuss what Kubernetes is, we will discuss the advantages of using minikube, and we will show the functionality of what Kubernetes can do with NodeJS. We will show how to scale your application, how to deploy multiple copies of your application based on metrics, and show how to master blue/green deployments to not lose any uptime during updating your application.

**Comment by tjwebb** [comment]
Troy's title: 

> Using minikube (Kubernetes) for local Node.js development
