### ISSUE TITLE
JavaScript AST Talk

### ISSUE THREAD

**Issue by qwo** [norfolkjs/logistics#119]
> Troy Connor [11:59 AM] 
Did anyone do a AST talk at Norfolk.js? :ninjacat:  
I’m not volunteering but it does sound like an awesome talk :smiling_imp:

> Stanley Zheng [12:04 PM] 
I’d do one

**Comment by moe-dizzle** [comment]
I would like do a talk about creating babel or eslint plugin using ast. maybe it can be after a theoretical talk about ASTs.

**Comment by lynnaloo** [comment]
Do you want to do a lightning talk in March?

**Comment by qwo** [comment]
sure sounds good

**Comment by moe-dizzle** [comment]
Yeah I def would too

**Comment by lynnaloo** [comment]
@Maurice-Hayward what is your talk title? The meetup is March 19th.

**Comment by qwo** [comment]
Retracting my interest to give this talk but if someone else wants to talk about it, that'd be 👌
