### ISSUE TITLE
January Agenda 

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#121]
January 15th - Lightning Talks

Food Sponsor: Cloudreach
Beer Sponsor: TBD
Location Sponsor: Pierce/McCoy
Events: PopUp Robots, RevolutionConf

Talk(s):

@stanzheng - Async Await
Matt Campbell - Web Assembly

- [X] Meetup Event
- [ ] Agenda @stanzheng 
- [X]  Food @lynnaloo
- [ ] Beer @lynnaloo
- [X] Venue

**Comment by troy0820** [comment]
Can we close this?

**Comment by qwo** [comment]
thanks for the headsup troy
