### ISSUE TITLE
Talk on Accessibility Basics ("Accessibility isn't Inaccessible") 

### ISSUE THREAD

**Issue by dylan-isaac** [norfolkjs/logistics#128]
A talk going over the the importance of a11y, how html semantic elements translate to the accessibility tree, and when to use aria attributes.

I won't be able to get this ready for May, but I would be down for June and onward.

**Comment by lynnaloo** [comment]
@dylansheffer I'm good with either of the talks you submitted. Can you do a lightning talk in November?

**Comment by dylan-isaac** [comment]
Sure, do you have a preference?

**Comment by lynnaloo** [comment]
Are you interested in giving this talk this month? Our second person for September hasn't stepped up yet.

**Comment by dylan-isaac** [comment]
I can do that if you don't mind an overlap with HRNUG. I'm giving the same a11y talk on September 11

**Comment by lynnaloo** [comment]
Nah, I think that's fine. You'd just need a shortened version since this is a lightning talk.

**Comment by dylan-isaac** [comment]
That works for me 👍
