### ISSUE TITLE
React-Native/Expo 

### ISSUE THREAD

**Issue by qwo** [norfolkjs/logistics#130]
I suggested if @reggie3 was interested in doing a React-Native/Expo talk

He mentioned he might be! 

Reggie has written about expo https://blog.expo.io/@reginald.johnson

and I believe he has done a session at FCC about it

**Comment by reggie3** [comment]
The FCC session I did was about building API's using Amazon Web Service's API Gateway and Lambda functions.  I'd be available to talk about Expo, or about those AWS items.

**Comment by qwo** [comment]
Whatever you'd like to talk about speakers choice!

**Comment by lynnaloo** [comment]
We’ve already had a few Serverless and FaaS talks, so I’d prefer Expo. We have a spot available in September.

**Comment by reggie3** [comment]
Expo it is then!  September should work well as long as I don't get deployed to respond to some contingency.  I'll keep my fingers crossed.

**Comment by reggie3** [comment]
@stanzheng @lynnaloo Would you like me to do a "show and tell" on creating a React Native app or would you prefer a workshop which walks the attendees through creating a RN app?  I think the workshop would be more interesting, but it would also take more time.

**Comment by lynnaloo** [comment]
@reggie3 I'm creating a new issue for September and I'll tag you in it. We typically do two shorter talks each meetup, so I think a 40 minute show-and-tell would be best.

**Comment by reggie3** [comment]
Show and tell sounds good.
