### ISSUE TITLE
September Agenda

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#131]
September 17th - Lightning Talks

Food Sponsor: TBD
Beer Sponsor: TBD
Location Sponsor: Pierce/McCoy
Events: Norfolk GoBridge Meetup, October Meetup, Beer.js Christmas Edition

Talk(s):

@reggie3 - "Creating React Native Mobile Applications Using Expo"
@dylansheffer "Accessibility isn't Inaccessible"

- [x] Confirm Speakers
- [x] Meetup Event
- [ ] Agenda
- [x]  Food
- [x] Venue

**Comment by lynnaloo** [comment]
@reggie3 you are all set to speak - let me know your talk title and I'll create the event.

**Comment by reggie3** [comment]
@lynnaloo How about "Creating React Native Mobile Applications Using Expo"

Also, should the date be September 18th?

**Comment by Seairth** [comment]
What day is it?  I'm guessing not June 18th.

**Comment by lynnaloo** [comment]
September 17th. Copy-paste error.
