### ISSUE TITLE
November Agenda

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#134]
June 18th - Lightning Talks

Food Sponsor: TBD
Beer Sponsor: TBD
Location Sponsor: Pierce/McCoy
Events: Beer.js Christmas Edition

Talk(s):

@dylansheffer
TBD

- [ ] Confirm Speakers
- [ ] Meetup Event
- [ ] Agenda
- [ ]  Food
- [ ] Venue

**Comment by dylan-isaac** [comment]
I can do a lightning talk on a11y or talk on using vscode, markdown, and gitlab for free cloud note taking
