### ISSUE TITLE
January Agenda

### ISSUE THREAD

**Issue by troy0820** [norfolkjs/logistics#135]
January ~~23rd~~ 14th, 2019

Beer Sponsor: TBD
Location Sponsor: The Birch
Events: 

- [ ] Meetup Event
- [x]  Venue

**Comment by lynnaloo** [comment]
@troy0820 Thanks for adding this 👍 We had tentatively planned on January 14th to avoid the holiday, but we decided (just yesterday) that we're going to move it to Beer.js this month and go big for Sharpen Your Saw next month. Can I confirm you for March instead?

**Comment by troy0820** [comment]
Yeah, March is fine, I may be on vacation but I can handle the agenda and try to look for a speaker.  I can still put the details for Beer.js this month and have the logistics for the event done.  @lynnaloo
