### ISSUE TITLE
Possible Speakers

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#21]
Pam Selle of Philly-JS-Dev/Comcast would like to come down to speak

**Comment by lynnaloo** [comment]
Hiro gave us a talk in December and Pam is coming down in April.

Would like to get Mike Hostetler down here too: http://appendto.com/team/mike-hostetler/ @tjwebb?

**Comment by jalbertbowden** [comment]
pam from philly? when is she speaking? bout what?

**Comment by tjwebb** [comment]
> Would like to get Mike Hostetler down here too: http://appendto.com/team/mike-hostetler/ @tjwebb?

cc @mikehostetler . Interested? If it works with your schedule, we'd love to have you give a talk on... anything. Or, if you want to just hang out, that's ok too.

> pam from philly? when is she speaking? bout what?

She's giving a talk on how to choose the right javascript framework for your project, and will go over a few of them. We'll announce the meetup soon, but it'll be on April 23.

**Comment by mikehostetler** [comment]
I'm coming that direction in late June.  Are you planning out that far yet?

6/24 - 6/28 I'm planning to be near Washington DC
6/29 - 7/1 I'll be near Virginia Beach & Norfolk

**Comment by jalbertbowden** [comment]
nice! great job guys. think i may climb out of the cave for one of these.

**Comment by tjwebb** [comment]
Cool. Giving people a reason to come out of the cave is, after all, what
norfolkjs is here for :)

**Comment by lynnaloo** [comment]
@jalbertbowden I made an event for Pam's talk, but I haven't announced it yet until she gives me a summary. Her book is on choosing frameworks, but not 100% sure about the talk yet. She's in Hacker School in NYC right now, so that might be something interesting to touch on as well.

**Comment by bmf** [comment]
Housekeeping
