### ISSUE TITLE
nodeschool

### ISSUE THREAD

**Issue by jalbertbowden** [norfolkjs/logistics#27]
there's a nodeschool event in pa coming up in april, wanted to send it to everyone in the group....is there a mailing list?

**Comment by lynnaloo** [comment]
Was talking to @jasonrhodes from NodeSchool Baltimore about coming down and doing a NodeSchool workshop. We could do it around the Tides baseball schedule so he can catch a game as well.

**Comment by bmf** [comment]
Are we looking at doing this in the spring of '16?

**Comment by lynnaloo** [comment]
I assigned myself and I'll ping Jason again to see what his schedule looks like for 2016.

**Comment by jasonrhodes** [comment]
Linda is great and I am the literal worst and yes ping me and we can talk about possibilities maybe for early next year or spring…

**Comment by lynnaloo** [comment]
@jasonrhodes I'm going to tentatively schedule you for April 20th. We can sponsor transportation and an overnight stay if need either/both.

**Comment by jasonrhodes** [comment]
OK sounds good! We can work out details as it gets a little closer. And let me know what your sponsorship needs/details are so I can pass them on...
