### ISSUE TITLE
Food sponsors

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#48]
We're looking for more sponsors specifically to provide food for the meetups. If you are interested or you know of a company that I need to reach out to, please comment below!

- Sarah Bray is going to talk to &Yet to see what they might do for out of state sponsorship.
- I'm going to bother back all of the recruiters that keep emailing me :)

**Comment by bmf** [comment]
@lynnaloo is this covered now or are we still looking for other sponsors?

**Comment by lynnaloo** [comment]
I'll close this and start a new issue for general sponsorship to keep open. We are constantly in need of sponsorship for everything except location at this point so the issue is a good reminder to organizers to keep asking companies that they have relationships with.
