### ISSUE TITLE
Speaker/Ideas for January

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#49]
January 19th - Unless Meteor gives us a better hard date for 1.0, this can be a place holder for @bretfisher's Meteor talk.

**Comment by lynnaloo** [comment]
We're going to reschedule @1kevgriff for another month or workshop since he has client obligations on the 19th. @tjwebb is going to go at it alone!

80/20 is sponsoring drinks and UDig is tentatively sponsoring food (haven't confirmed what kind of food yet).

**Comment by 1kevgriff** [comment]
Sorry :(  



Maybe I could do an IO.js talk :)

**Comment by lynnaloo** [comment]
No problem! We'll put you on the calendar for later this year :)
