### ISSUE TITLE
Speaker/Ideas for March

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#51]
March 18th - Beer.js - location TBD

**Comment by lynnaloo** [comment]
I'm thinking about doing this at the Birch again since they have been so good to us, but I'm open to idea if anyone has a particular beer joint that they like.

**Comment by stanzheng** [comment]
binary of O'Connors and Birch has been OK.

I can try to talk to smartmouth again in person to see if we can make it work.

**Comment by lynnaloo** [comment]
Yes, that would be great!

**Comment by lynnaloo** [comment]
I planned this again at the Birch since they have been so great. If the numbers look bigger than the Birch can support, we'll move to O'Connor's or Public House.
