### ISSUE TITLE
Meetup Perks

### ISSUE THREAD

**Issue by stanzheng** [norfolkjs/logistics#55]
Meetup perks were deprecated and now we have to replace the promo codes. I forget what all 5 vendors were but ill go off the top of my head

- [x] oreilly

- Buy ebooks at 50% off and print books at 40% off: When you purchase a book or ebook on oreilly.com use the UG Program discount code: DSUG

- Buy 1 Ebook, Get 1 Free with your user group discount code: DSUG2

- [x] manning

- We have a standing discount all your members can use to save 36% on any purchase at manning.com. Just enter ‘ug367’ in the Promotional Code box when you check out at manning.com. Feel free to post this code on your website or in your newsletter.
- [x] starch press 
- [ ] more here

**Comment by bmf** [comment]
Housekeeping
