### ISSUE TITLE
Hour of Code

### ISSUE THREAD

**Issue by bmf** [norfolkjs/logistics#61]
Looks like we might miss the official week for the Hour of Code (Dec 8-14), but that shouldn't stop us from hosting one!

**Comment by lynnaloo** [comment]
The Makerspace did 3 weeks of kids/adults Hour of Code in December and it was pretty popular. I'm thinking maybe close this and defer to helping with that class the next time it's offered there rather than hosting our own.

**Comment by bmf** [comment]
Agreed. 

Brandon Flade
