### ISSUE TITLE
Announcements for 1/19 Meetup

### ISSUE THREAD

**Issue by bmf** [norfolkjs/logistics#62]
This will be our 1 year anniversary. Our first meet up was a Hang out + Interactive talk on Angular JS. According to Meetup.com, we had a whopping total of 26 JS Ninjas. A lot has happened in a year...

**Comment by bmf** [comment]
I requested Eloquent JavaScript, 2nd Edition and Linux Command Line from No Starch on 1/5. Haven't heard from them yet, probably will later today.

**Comment by lynnaloo** [comment]
We should probably mention the 50% Pact discount on ebooks if @stanzheng has the details.

**Comment by bmf** [comment]
50% off any ebook in our catalgoue:
PACKT

**Comment by stanzheng** [comment]
code is: JAitlhI0
