### ISSUE TITLE
The raffle

### ISSUE THREAD

**Issue by bmf** [norfolkjs/logistics#63]
Moving the raffle helped a bit, but I think we had too many items to give away and it was still very chaotic. 

What if we did something along these lines: 

A) Offer a max of 3 prizes per meet up
B) Instead of a raffle, we create a mobile site that offers up challenges for the prizes. These can either be JS trivia or challenges that pit the players against each other. At the end of the meet up the winners can claim their prize.

**Comment by lynnaloo** [comment]
https://github.com/norfolkjs/meetup-door-prize

This could use some serious improvements but it's a good starting place.

**Comment by bmf** [comment]
Housekeeping
