### ISSUE TITLE
NodeBotsDay 2015

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#64]
Date is Saturday, July 25th. Location is 757 Makerspace.

We already have some Pawel-bots and we can get more of those kits pretty easily (cheaply). We can likely get the Flexbot drone kit < $50 so that's another great project. Other ideas are NodeCoptors, NodeBoats, and NodeRockets. Let's comment here with a list of crazy ideas and we'll organize them into a plan as the date gets closer.

**Comment by bmf** [comment]
I like the noderockets idea. Can we do that at 757 Makerspace? I also like the bot battle we did last year. We could do an obstacle course for Nodebots/boats/copters...

**Comment by bmf** [comment]
I think for the bot battle, we should make that competition a "Bring Your Own Equipment" and set some parameters for participation. Things like - No projectiles, Flames, common size for participant bots, etc... We should also have a waiver for potential equipment damage.

**Comment by lynnaloo** [comment]
I'll get the rules/requirements that they use for RobotsConf. I know for JSConf soccer, it was a free-for-all with whatever people could find to use for their bots.

**Comment by bmf** [comment]
I think you're right about sponsorship covering our equipment. My concern was more so about people bringing their own equipment and it getting broken during a battle bots competition. Maybe a soccer-bot competition is the way to go?

**Comment by lynnaloo** [comment]
Soccer is still pretty full contact. At least a disclaimer for people bringing their own equipment is probably a good idea. That's probably something else that we might be able to copy from other bigger groups.

**Comment by bmf** [comment]
Cool. It'll be nice to see how they do it.

**Comment by bmf** [comment]
We will probably want to do an Internet of Things (IoT) talk a couple of months prior to get people thinking about JS hardware development. I'm thinking May will be a good time. Also, Avengers: Age of Ultron comes out on May 1. I might be making a stretch here, but my thinking is people will be more sensitive to robots, hardware, and cool tech at that time. We can use that and ride the wave into July. So, interested in doing an IoT talk with me?

**Comment by lynnaloo** [comment]
Another way to get people excited about robots and hardware is Popup Robots (hint hint). End of May is JSConf, so probably best to do something between then and NodeBotsDay. There's always hardware in the swag bag and a whole day of hacking for whoever goes to bring back to the 757.

**Comment by bmf** [comment]
I thought Popup Robots was a given. ;) June then?

**Comment by lynnaloo** [comment]
Do you want to start some issues in your pop-up robots repo? I'm down for June.

**Comment by bmf** [comment]
issue started for Popup Robots meet up #2

**Comment by lynnaloo** [comment]
We definitely need to include Pawel's IKEA-like instructions for the Sumobots: https://github.com/makenai/sumobot-jr/blob/master/sumobot-instructions.pdf.

**Comment by lynnaloo** [comment]
For this year, I'd like to open up the back door of the Makerspace and do NodeBoats and NodeCopters. I also have some Arduino Bits running on JavaScript so Little Bits might be an interesting "station" to setup as well. I'm going to be on the lookout before July also for another 4-5 dedicated volunteers to help people build and code the bots.

**Comment by bmf** [comment]
The flight area you are talking about is right next to the parking lot. This makes me think there might be a possibility of personal property damage due to an inexperienced operator or whatever. Doesn't that open us up to some liability if something like that were to happen?

**Comment by bmf** [comment]
To clarify, I'm thinking an outside demo of a Nodecopter would be cool, but having multiple inexperienced people flying them in that tight of an area might be a bad idea.

**Comment by lynnaloo** [comment]
757 Makerspace has already been doing some drone flying in that area on Fridays/Sundays so for free-flying we have the option to use their rules/format. For kids and inexperienced flyers, we can setup physical barriers and also limit the actions with the code they're running. With Node, we can set a queue of specific actions so they do a controlled flight (possibly through obstacles).
