### ISSUE TITLE
Books/Swag for February

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#66]
Thread to keep track of books/swag requested.

@bmf  - No Starch
@stanzheng - O'Reilly/Manning/Pact

I will check with PluralSight and Wintellect for our annual box of swag to give out for free.

**Comment by bmf** [comment]
No Starch - Ordered If Hemingway Wrote JavaScript and JavaScript for Kids.

**Comment by stanzheng** [comment]
Requested but no confirmation on shipping yet. 
Oreilly
---
3x  JavaScript the good Parts
Packt
---
Node Cookbook: Second Edition
Cookbook
David Mark Clements
April 2014
ISBN 139781783280438


Node.js Design Patterns
Mario Casciaro
December 2014
ISBN 139781783287314


Mastering D3.js
Pablo Navarro Castillo
August 2014
ISBN 139781783286270

**Comment by lynnaloo** [comment]
I emailed PluralSight (also now CodeSchool) and they said every year we have to re-apply for sponsorship to get another box of swag. So I just submitted the information for this year.

**Comment by stanzheng** [comment]
O'Reilly is switching to an e-book model for usergroup books so members will now be able to go on and pick titles like Manning.

**Comment by stanzheng** [comment]
Packt has requested and their books are in the mail.

**Comment by tjwebb** [comment]
word

**Comment by lynnaloo** [comment]
What's the current book status?

**Comment by tjwebb** [comment]
I think no starch isn't worth wondering every month whether no starch books are going to get here. That's my status.

thoughts? I propose we drop them and move on

**Comment by lynnaloo** [comment]
I just put these issues in here so I know what books we have to raffle. More importantly, that we have at least one book to raffle.

**Comment by qwo** [comment]
heres a pic, we got plenty  .. 
if someone has some favorite titles to pick for next month let me know ... https://www.packtpub.com/all?search=&type_list%5Bbooks%5D=books&offset=&rows=&sort=
![img_20150236_191225_1024](https://cloud.githubusercontent.com/assets/3683993/6240046/f4181c3a-b6d7-11e4-8d4d-510a039540c9.png)

**Comment by lynnaloo** [comment]
@stanzheng Don't forget to bring a couple tonight for raffles.
