### ISSUE TITLE
Speaker/Ideas for April

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#67]
If everything works out, I'd like to have this event at the Slover Library and get a sponsor to pay for catering.

**Comment by lynnaloo** [comment]
Looking at getting Pam Selle here again! We'll need to put her up in the Grow hotel and get a sponsor to cover plane fare (~$300). 

Slover is open to host us that night, but just need to figure out cost and catering.

**Comment by qwo** [comment]
confirm will that be on third monday, April 20th or another day?

**Comment by lynnaloo** [comment]
No, it would have to be a Thursday because of her Hacker School schedule. I will also be in Montreal earlier that week.

**Comment by qwo** [comment]
ok cool April 23rd it is.

**Comment by lynnaloo** [comment]
ETA is going to sponsor Pam's airfare, Dominion Enterprises is going to sponsor food, and CodeBetter will cover the Slover's free (unknown as of right now). Also, the 3rd Thursday is the 16th, not the 23rd.

**Comment by qwo** [comment]
this sounds amazing. pumped +1

**Comment by lynnaloo** [comment]
OK, I did end up booking this on the 23rd so that it would workout with the Slover schedule. She quoted me the cost of $80, so that will be covered by the CodeBetter sponsorship. I will set it up with Dominion to pay the catering costs as we get closer to the event.

**Comment by lynnaloo** [comment]
@stanzheng Will you verify that Hotel Grow is available that night?

**Comment by qwo** [comment]
ill pass a request along :). Is that for just the night of April 23rd?

**Comment by lynnaloo** [comment]
If they can't sponsor the Growtel (see what I did there?), then maybe they'll sponsor another place for her to stay? 

Also, 80/20 will be sponsoring a round of drinks after the Meet-up at the Taproom downtown.

**Comment by lynnaloo** [comment]
I got Pam's plane flights so she'll definitely be in on the 23rd. We still need to figure out her accommodations for that night. I'm tasking @stanzheng with that :)

DE is now not paying for our catering costs so I'm going to talk to Tek Systems about covering it instead.
