### ISSUE TITLE
Books/Swag for April

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#68]
Thread to keep track of books/swag requested.

@bmf  - No Starch
@stanzheng - O'Reilly/Manning/Packt

Anything else we might get to put on the free-for-all table.

**Comment by tjwebb** [comment]
should we remove no starch?

**Comment by bmf** [comment]
Not yet. I have books from last month and I still expect books from this month, although they will most likely be late. I'll reach out to them after the meet up to see if we can come to an arrangement, if not we'll drop them as a sponsor.

**Comment by tjwebb** [comment]
ok

**Comment by lynnaloo** [comment]
We still have two books from Pact + O'Reilly e-books. I'll see about getting Pam's book as well since she's the speaker.

**Comment by bmf** [comment]
I also still have our last batch from nostarch. We should remove them as a
sponsor after we give these away tho.

**Comment by lynnaloo** [comment]
What do we have in the way of swag? I have two books left here from Pact: Node Cookbook and D3.

**Comment by qwo** [comment]
Packt never responded back. Theres always Manning and O'Reilly, no physical copies

**Comment by bmf** [comment]
I think I have 2 No Starch books left. I'll let you know when I get home.

**Comment by lynnaloo** [comment]
Whoever has swag, don't forget to bring it on Thursday! @bmf @stanzheng
