### ISSUE TITLE
NorfolkJS 2015 Outlook

### ISSUE THREAD

**Issue by stanzheng** [norfolkjs/logistics#69]
Meeting notes January 18 
Cafe Stella 10:30am 

Agenda
---
- January - Travis Webb [ES6]
- February  - Steve Hackbarth  [async]
- March - Off (Beer.js/Pop-up Robots)
- April - 
- May - 
- June - "Internet of Things" - Brandon & Linda
- July - International NodeBots Day + ?
- August - Off (Beer.js/Pop-up Robots)
- September -
- October - 
- November
- December - Off

Mission
---
- less frameworks, more core javascipt improving skills
- learn to contribute to open source 
   - publish an npm module
   - github 
   - unit testing
- write more javascript
  - https://github.com/norfolkjs/local-projects 
  - contribute to open source 

Speakers 
---
- March Cristian_Arcega (https://www.crowdismo.com/project/cristian-arcega-dream-build)?
- Ken Collins - Unit Testing
- RVA.js James Long 
- Kevin Griffin 
- Pam Sele

Topics
---
- Beer.js
- Internet of Things
- Unit Testing 
- Performance
need to happen per event
----
- food
- venue
- video spots  
- items  
    - raffle 
    - swag 
- reminder
- agenda 
- speaker
- running the event

**Comment by lynnaloo** [comment]
https://github.com/norfolkjs/general-info/wiki/Things-for-Each-Meetup
