### ISSUE TITLE
React Study Group

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#73]
Looking to do a less-formal React/Flux study group maybe starting a little earlier than usual (5:30) at Slover and going until whenever people are done or the library closes.

I'm thinking first week of March so it doesn't collide with any other meetups or Robots/Beer.js.

**Comment by troy0820** [comment]
If you do this in April, can it NOT be the week of the 13.  I know we have a pop-up robots event that week but I should be out of town and I don't wanna miss this.

**Comment by lynnaloo** [comment]
Maybe we can shoot for the last week of the month or early May. @tjwebb and I both want to do it, but we've been busy on alternate weeks.

**Comment by lynnaloo** [comment]
@tjwebb Is going to do an intro talk in May to get us kicked off, but we'll probably still do sporadic study groups for anyone who is interested in hacking React.

**Comment by lynnaloo** [comment]
I'll go ahead and close this one and @yejodido can start a new thread for the proposed "front-end" meetup + coffee.
