### ISSUE TITLE
Agenda Items for April Meetup

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#74]
Sponsors: Grow (hotel), Tek Systems (food), CodeBetter.com (slover fee), 80/20 Consulting (drink-up afterward)
- Placeholder for Tessel.io discount (don't place somewhere on the interwebs)
- 80/20 is hosting an drink-up at Tap Room for an hour after the meet-up
- Next PopUp Robots Date

**Comment by bmf** [comment]
add Balderdash

**Comment by bmf** [comment]
add Building the Slover library panel discussion 
Tuesday, April 28at 11:45am - 1:00pm in EDT

**Comment by tjwebb** [comment]
http://balderdash.co/img/logo.jpg
