### ISSUE TITLE
May Agenda

### ISSUE THREAD

**Issue by bmf** [norfolkjs/logistics#77]
Need:
- Sponsor list
- Graphic for the Slack Announcement (animated gif?)
- Upcoming events list
- List of discounts we want to mention
- Speaker name and title of talk

**Comment by bmf** [comment]
Sorry @jalbertbowden, I clicked the wrong name.

If anyone knows how to un-assign, please let me know. Not seeing it in help.

**Comment by bmf** [comment]
Or I guess, I did figure it out. I think I need more coffee. </endspam>

**Comment by lynnaloo** [comment]
Sponsors are Hatch (Location), 80/20 (beer), UDig (tacos).
Dominion Enterprises and CodeBetter.com are our re-occuring monetary sponsors.

Upcoming Events:
NodeBotsDay 7/27. Still looking for more volunteers for teaching, coordinating, etc.

**Comment by jalbertbowden** [comment]
de is a sponsor? i thought this group was started to be open because de wasn't

**Comment by lynnaloo** [comment]
By "monetary sponsor" I mean that they're giving us money for food/fees/etc to support having our meet-ups in public spaces like the library and the arts district. It unfortunately costs us a lot more to not meet in local business spaces.

**Comment by tjwebb** [comment]
@jalbertbowden Norfolk.js has numerous recurring expenses. DE providing some money for this does not make the group any less open, it actually helps ensure that we can continue doing what we've been doing. If a sponsor attaches any conditions to sponsorship which contradict the values of the group, we will not accept it.

**Comment by metaskills** [comment]
AGREED - DE is now sponsoring the 757.rb in the same way too. Really proud of them ramping up. Baby steps for this area getting better. Hopefully optimistic!

**Comment by jalbertbowden** [comment]
everything runs on money
thats kewl

On Thu, May 7, 2015 at 7:48 AM, Ken Collins notifications@github.com
wrote:

> AGREED - DE is now sponsoring the 757.rb in the same way too. Really proud
> of them ramping up. Baby steps for this area getting better. Hopefully
> optimistic!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/norfolkjs/logistics/issues/77#issuecomment-99830154.

## 

J. Albert Bowden II

jalbertbowden@gmail.com

http://bowdenweb.com/
