### ISSUE TITLE
Slides/Agenda for August 2015

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#80]
Speaker Matt Campbell
Location: Hatch
Food sponsor: Balderdash/Draft
Drink sponsor: 80/20 consulting
Swag: Treehouse t-shirts, also need to get books from book sponsors

**Comment by lynnaloo** [comment]
@bmf @stanzheng What do we have in the way of raffle stuff? I know we have Treehouse swag and I have some random JSConf swag as well.

**Comment by qwo** [comment]
haven't made a request yet i will follow up this week. otherwise no stuff
on hand

On Sun, Aug 9, 2015 at 1:43 PM, Linda Nichols notifications@github.com
wrote:

> @bmf https://github.com/bmf @stanzheng https://github.com/stanzheng
> What do we have in the way of raffle stuff? I know we have Treehouse swag
> and I have some random JSConf swag as well.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/norfolkjs/logistics/issues/80#issuecomment-129221504.

## 

Stanley Zheng

**Comment by bmf** [comment]
Slides are up.
