### ISSUE TITLE
Speaker/Ideas for September

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#81]
- Joey D. is talking on Inline Css
- Pierce/McCoy is giving us meeting space
- Going with Brutti's Catering for food
- Travis is talking to DE for other sponsorship to promote their hack event

**Comment by troy0820** [comment]
Brutti's in Portsmouth? They have pretty great food

**Comment by lynnaloo** [comment]
Yeah, I know the owner so I think we can get a better deal.
