### ISSUE TITLE
Slides/Agenda for September 2015

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#82]
### Sponsors
- Pierce/McCoy Law (location sponsors)
- 80/20 Beer sponsor
- CodeBetter.com (default sponsor)
- Balderdash (food/drinks)
### Events
- Meetup of Meetups - Oct 1st at Public House
- Meteor Worldwide Hackathon - Oct 10th (Paul Chin organizer)
- Pop-up Robots - Oct 15th
- Next Norfolk.js meetup - Unit Testing with Ryan Quinn - Oct 19th
- Hack to Help - Oct 23-24 - Dominion Enterprises
- HrDevFest Nov 13th/14th
- Harbor Lights 5K 757Dev Team - Nov 20-22nd

**Comment by bmf** [comment]
Slides are up.

**Comment by bmf** [comment]
http://rawgit.com/norfolkjs/general-info/master/announcements/september_2015.html#/

**Comment by nogtini** [comment]
Slides for tonight: 

https://docs.google.com/presentation/d/1fcK6CxhDfpvHUIXsBpbXLsx5Bu6AwNMkDt839LSnTXc/edit?usp=sharing
