### ISSUE TITLE
Turbo Applications - Winning with Ajax + pushState + Rails

### ISSUE THREAD

**Issue by metaskills** [norfolkjs/logistics#85]
So I just finished up a Rails app that leverages Turbolinks v3 and I can't wait to share the details. I'd love to do a presentation for NorfolkJS and advertise to 757rb too. What do y'all think? Obviously, I will come up with  better title & description if we can set a date.

**Comment by metaskills** [comment]
WOW, I actually put half the talk together this weekend. Even tho Rails is in the title, this application methodology is agnostic and adopted by other language/frameworks like Python, Django, PHP, Grails, ASP.NET, etc.

Don't worry, half the talk is purely on the JavaScript lib and what it is doing. What do y'all think?

**Comment by qwo** [comment]
Sounds like a diverse topic. @lynnaloo mentioned in #84 that November slot might be taken this year and we have Beer.js in December. Have to wait for her to chime in to confirm but the next free Norfolk.js might be after the new year.

Any thoughts about cross-organizing it under polyglot or we could make a mirror event for November if you're planning to have it then under @757rb.

**Comment by lynnaloo** [comment]
Sorry, I saw this and forgot to respond. I think this looks really cool, but :+1: to what @stanzheng said, our next spot is January as of right now. What about submitting it to hrdevfest? This is the last week to submit talks and that would be a good polyglot audience.

**Comment by lynnaloo** [comment]
We're tentatively planning for 2016 if you want to get in there for Jan/Feb @metaskills

**Comment by lynnaloo** [comment]
I think this is stale @metaskills, but you should submit another topic or come give us a lightning talk!
