### ISSUE TITLE
Slides/Agenda for October 2015

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#86]
### Sponsors
- Pierce/McCoy
- CodeBetter.com 
- 80/20
### Events
- Hack to Help - Oct 23-24 - Dominion Enterprises
- Next Norfolk.js meetup - "It’s Components All The Way Down" - Blain Price on Nov 16th
- Pop-up Robots - Nov 19th
- HrDevFest Nov 13th/14th
- Harbor Lights 5K 757Dev Team - Nov 20-22nd

**Comment by qwo** [comment]
past date
