### ISSUE TITLE
January Agenda

### ISSUE THREAD

**Issue by bmf** [norfolkjs/logistics#89]
January 18th 2016

Food sponsor -Dominion Enterprises
Beer sponsor - 80/20
Location sponsor - Pierce/McCoy
Events - PopUp Robots, Fez, Revolution Conf (leave this on the slides until May 13th)

Lightning Talks (5 min) - Stanley Zheng and Paul Chin
Frances Coronel will be the feature presentation.

We can remove CodeBetter from the general slide deck since their support will now be sporadic.

**Comment by lynnaloo** [comment]
Speaker is going to be Frances Coronel - Topic TBD

**Comment by qwo** [comment]
@ChrisSpillers might be interested in doing a lightning talk about client unit testing

**Comment by lynnaloo** [comment]
@pchinjr is going to do a 5 minute lightning talk. Does Chris was to do longer than 5?

**Comment by ghost** [comment]
A 5 minute lighting talk works for me.

**Comment by qwo** [comment]
@chrisspillers it looks like #90 also still open, if you'd like to do a 10 minute lightning or need more time :). I just made a suggestion.

**Comment by ghost** [comment]
The topic can be adapted well to fit any time duration.  I'll propose a full talk for February in #90 and I can scale it down to a lighting talk if needed.

**Comment by lynnaloo** [comment]
We already have full-length talks setup until May really (I'm behind updating Github), so I longer-than-usual lightning talk in February or March would be great.

**Comment by ghost** [comment]
Ok cool, I'll prepare for a lighting talk in Februrary then.

**Comment by lynnaloo** [comment]
:+1:

**Comment by pchinjr** [comment]
Hi everyone, working title of my lightning talk is going to be "Pull Requests Are Magic". I'm stoked to work on it and present.

**Comment by tjwebb** [comment]
+1

**Comment by bmf** [comment]
+1 for giving a lightning talk.
You can earn an extra +1 by adding a screen shot from Netflix's The Ridiculous Six with the caption "That's some mystical shit!"

P.S. I wouldn't recommend that movie to my worst enemy, but I think the quote is appropriate.

**Comment by stanzheng** [comment]
+1 

also to be super flaky i probably won't have a talk prepared (anything interesting enough) to talk about by next meetup. so @pchinjr add extra gifs! can you do 10 minutes?

**Comment by lynnaloo** [comment]
+1 to @bmf who had the idea that we should add lightning talks
