### ISSUE TITLE
February Agenda

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#90]
Feb 15th

Food sponsor: SSI (contact Josh Lumley josh@supersystemsinc.com)
Beer sponsor: 80/20
Travel sponsor: Balderdash
Lodgin sponsor: Grow
Location sponsor: Pierce/McCoy
Events: PopUp Robots, 
Fez, 
Revolution Conf (call for speakers is done, but tickets open soon), 
Tech-Connect: 
http://www.meetup.com/757-Polyglot-Developers/events/228788665/

Feature Presentation: 3rd Annual Sharpen Your Saw (@shackbarth)
Lightning Talk (10 minutes) - @chrisspillers

**Comment by ghost** [comment]
I would be interested in presenting on the current tools/techniques for client-side unit testing.  I can build a full presentation/demo and scale it down to a lighting talk as needed.

**Comment by ghost** [comment]
^ make that a lighting talk per #89

**Comment by ghost** [comment]
Lightning talking *

**Comment by lynnaloo** [comment]
@chrisspillers - @shackbarth is doing something related to testing for his Sharpen Your Saw talk/workshop if you guys want to coordinate?

**Comment by ghost** [comment]
@lynnaloo good idea.  @shackbarth I am planning to do a quick 5 min. lightning talk covering the current ecosystem for writing/running client-side unit tests and automated E2E testing.  What type of testing/tooling do you plan to cover?

**Comment by shackbarth** [comment]
The tool I'm planning to go over is mocha (with a bit of webpack or browserify) but one viewpoint I'm going to push is that you shouldn't need to use the DOM to unit-test your clientside business logic. So I'll likely throw some shade on karma/jest/jsdom/etc. Browser-based e2e testing, on the other hand, I'm going to position as a great idea that's outside the subject of my talk.

So it would be safe and complementary for you to go over Protractor/etc! Then again I'm hoping for a discussion with a bunch of different viewpoints by the end, so don't let me scare you away from advocating for something like Karma.

**Comment by ghost** [comment]
Ok cool, to complement your presentation how about I discuss e2e testing on the Mocha + Chai/WebDriverJS/Selenium stack?

**Comment by ghost** [comment]
Do the lightning talks generally go before the main presentation?  If that's the case and my lightning talk is more or less an e2e testing extension of yours then maybe I should present after you?

**Comment by lynnaloo** [comment]
@chrisspillers your talk will be just before Steve's so you should have some time in the beginning to figure out logistics.

**Comment by ghost** [comment]
Ok cool.

**Comment by bmf** [comment]
announcements are up. http://rawgit.com/norfolkjs/general-info/master/announcements/february_2016.html#/5

**Comment by ghost** [comment]
My slides: http://slides.com/chrisspillers/browser-e2e-testing

**Comment by qwo** [comment]
awesome talk @chrisspillers ! Really enjoyed it

**Comment by ghost** [comment]
@stanzheng ty!  I'm happy to hear that and really appreciated having the chance to present :)
